name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Enable .NET Framework 3.5
      run: |
        dism /online /enable-feature /featurename:netfx3 /all /quiet /norestart
      shell: cmd

    - name: Run Build.cmd
      run: |
        cd Build
        .\build.cmd
      shell: cmd

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        name: ConfuserEx Custom Build ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          Build\ConfuserEx_bin.zip